#! /bin/bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
	PINK=$(echo "#00897b")
    NORDIC=$(echo "#2d555b")
    NAVY=$(echo "#051014")
}
getcolors

## Configurations -------------------------------#
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$NORDIC"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$BLUE"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# special rules
#bspc rule -a termite-float state=floating follow=on focus=on
#bspc rule -a Pcmanfm state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Emacs state=tiled


## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager

# Lauch notification daemon
#dunst \
#-geom "280x50-10+40" -frame_width "1" -font "Iosevka Custom 9" \
#-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$MAGENTA" \
#-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$MAGENTA" \
#-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &
dunst &

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L+Spacebar' &
ksuperkey -e 'Super_R=Alt_L+Spacebar' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Restore wallpaper
nitrogen --restore &

# Java app problem
wmname LG3D &

exec picom --experimental-backends &
bash /home/icarus/.config/polybar/launch.sh --docky &
exec touchegg &
exec tlp --start &
sudo chmod 646 /sys/class/backlight/intel_backlight/brightness &
#exec polybar main -c $HOME/.config/polybar/config &
#exec polybar right -c $HOME/.config/polybar/config &
#exec polybar center -c $HOME/.config/polybar/config &
#exec polybar centerspotify -c $HOME/.config/polybar/config &
exec  &
exec polybar-msg cmd restart &
exec betterlockscreen -u /home/icarus/Pictures/Wallpapers/6161848c443d6.jpg&
exec sct 3800 &
/usr/lib/polkit-1/polkit-agent-helper-1 &
# Issue Tracker (Don't Remove IT)
issue_tracker.sh

