#! /bin/bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:' | awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:' | awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:' | awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:' | awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:' | awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:' | awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:' | awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:' | awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:' | awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:' | awk '{print $NF}')
	PINK=$(echo "#00897b")
	GRUV=$(echo "#ac9f82")
	NAVY=$(echo "#293b4c")
}
getcolors

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$GRUV"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$BLUE"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# remove all rules first
bspc rule -r *:*

# special rules
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'

#bspc rule -a termite-float state=floating follow=on focus=on
#bspc rule -a Pcmanfm state=floating follow=on focus=on

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager
exec picom &
dunst &
sxhkd &
xfce4-power-manager &
xfsettingsd &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
wmname LG3D &
bash /home/icarus/.config/polybar/launch.sh --cuts &
eww daemon &
exec betterlockscreen -u /home/icarus/Pictures/Wallpapers/soviet1.png &
exec xss-lock -- betterlockscreen -l &
exec flameshot &
libinput-gestures-setup start &
/usr/lib/polkit-1/polkit-agent-helper-1 &
